name: audio_web
description: Web App for ESP32 Audio Player
version: 0.1.0
repository: https://github.com/tbuen/audio-web

environment:
  sdk: ^3.5.3

dependencies:
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.0.0
